export * from './all/program.controller';
export * from './all/webinar.controller';
export * from './all/contact.controller';
export * from './all/event.controller';
export * from './all/news.controller';
export * from './all/branch.controller';
export * from './all/team.controller';
export * from './all/video.controller';
export * from './all/version.controller';
